export const dossierContent = {
  en: {
    ariaLabel: 'System Profile Dossier',
    closeAria: 'Close modal',
    windowTitle: 'system_profile.classified',
    classifiedBar: 'CLASSIFIED — INTERNAL PROFILE',
    systemProfile: 'System Profile',
    name: 'SAEED',
    endStamp: 'END OF FILE — DO NOT DISTRIBUTE',
    closingNote: 'You found this because you were looking carefully. That matters.',
    rows: [
      { label: 'Status', value: 'Active' },
      { label: 'Full Name', value: 'Saeed Zarrini' },
      { label: 'Classification', value: 'Senior Graphic Designer · Packaging Specialist' },
      { label: 'Years Active', value: '16+ Years (Est. 2007)' },
      { label: 'Primary Discipline', value: 'Pharmaceutical Packaging Design' },
      { label: 'Secondary Discipline', value: 'Visual Identity & Brand Systems' },
      { label: 'Tertiary Discipline', value: 'UI/UX Design · Web Development' },
      { label: 'Design Stack', value: 'Photoshop · Illustrator · Adobe XD · Figma · InDesign' },
      { label: 'Build Stack', value: 'WordPress · HTML · CSS · JavaScript' },
      { label: 'Current Clients', value: 'Nafas Pharmed · Busun Pharmed' },
      { label: 'Profile ID', value: 'SRD-SZ-2007 / CONFIDENTIAL' },
    ],
  },
  fa: {
    ariaLabel: 'پروندهٔ پروفایل سیستم',
    closeAria: 'بستن پنجره',
    windowTitle: 'system_profile.classified',
    classifiedBar: 'طبقه‌بندی‌شده — پروفایل داخلی',
    systemProfile: 'پروفایل سیستم',
    name: 'سعید',
    endStamp: 'پایان پرونده — تکثیر ممنوع',
    closingNote: 'این را پیدا کردید چون با دقت نگاه می‌کردید. این مهم است.',
    rows: [
      { label: 'وضعیت', value: 'فعال' },
      { label: 'نام کامل', value: 'سعید زرینی' },
      { label: 'طبقه‌بندی', value: 'طراح گرافیک ارشد · متخصص بسته‌بندی' },
      { label: 'سال‌های فعالیت', value: '۱۶+ سال (از ۱۳۸۶)' },
      { label: 'تخصص اصلی', value: 'طراحی بسته‌بندی دارویی' },
      { label: 'تخصص دوم', value: 'هویت بصری و سامانه‌های برند' },
      { label: 'تخصص سوم', value: 'طراحی UI/UX · توسعه وب' },
      { label: 'پشته طراحی', value: 'Photoshop · Illustrator · Adobe XD · Figma · InDesign' },
      { label: 'پشته ساخت', value: 'WordPress · HTML · CSS · JavaScript' },
      { label: 'مشتریان جاری', value: 'Nafas Pharmed · Busun Pharmed' },
      { label: 'شناسه پروفایل', value: 'SRD-SZ-2007 / CONFIDENTIAL' },
    ],
  },
};
