/**
 * Terminal localization notes:
 * - Window chrome (traffic lights, `>` prompt) stays LTR even in fa mode.
 * - Displayed text is translated; in fa mode both Persian and English
 *   command names are accepted (e.g. `help` and `راهنما`).
 * - Mono/system register keeps Latin digits and tech names where they
 *   read as instrument output.
 */

export type TerminalCommandId =
  | 'help'
  | 'whoami'
  | 'skills'
  | 'projects'
  | 'contact'
  | 'coffee'
  | 'clear';

const EN_COMMANDS: Record<Exclude<TerminalCommandId, 'clear'>, string[]> = {
  help: [
    '┌─ Available Commands ──────────────────────────',
    '│  help       — show this message',
    '│  whoami     — display user profile',
    '│  skills     — list technical capabilities',
    '│  projects   — browse selected work',
    '│  contact    — get contact information',
    '│  coffee     — essential fuel',
    '│  clear      — clear terminal output',
    '└───────────────────────────────────────────────',
  ],
  whoami: [
    '',
    '  NAME    Saeed Zarrini',
    '  ROLE    Graphic Designer · Packaging Specialist · Developer',
    '  EXP     16+ years (Est. 2007)',
    '  BASE    Independent Studio — Remote-First',
    '  MODE    Precision & Creativity',
    '',
    '  "I don\'t design to impress. I design to work."',
    '',
  ],
  skills: [
    '',
    '  ── DESIGN ─────────────────────────────────────',
    '  ▸ Photoshop / Illustrator         ████████████ Master',
    '  ▸ InDesign / XD / CorelDRAW       ███████████░ Expert',
    '  ▸ After Effects / Premiere        █████████░░░ Advanced',
    '  ▸ Pharma Packaging / UI-UX        ████████████ Master',
    '',
    '  ── FRONTEND ───────────────────────────────────',
    '  ▸ React 18/19 · TypeScript        ██████████░░ Expert',
    '  ▸ Next.js · Vite · Tailwind       █████████░░░ Advanced',
    '',
    '  ── BACKEND ────────────────────────────────────',
    '  ▸ PHP · WordPress                 ████████████ Master',
    '  ▸ FastAPI · MySQL · PostgreSQL    █████████░░░ Advanced',
    '',
    '  ── NATIVE ─────────────────────────────────────',
    '  ▸ Kotlin · Jetpack Compose        ████████░░░░ Advanced',
    '  ▸ Tauri v2 · Rust                 ███████░░░░░ Advanced',
    '',
    '  ── AI & BOTS ──────────────────────────────────',
    '  ▸ Anthropic · OpenAI · Gemini     █████████░░░ Advanced',
    '  ▸ OpenRouter · Telegram · Bale    ████████░░░░ Advanced',
    '',
  ],
  projects: [
    '',
    '  001  DbsPulse              — FastAPI / React / Postgres',
    '  002  Second Brain (SOL)    — Kotlin / Compose / SQLCipher',
    '  003  DbsKeep v0.2.5        — Tauri v2 / Rust',
    '  004  Nafas AI              — React 19 / PHP 8 / MySQL',
    '  005  Nafas Chatbot Pro     — WordPress / Gemini',
    '  006  Elementor Carousel    — PHP / Elementor',
    '  007  EsiFit                — React 18 / TS / Vite',
    '  008  Hesabyar              — PHP / MySQL / PWA',
    '  009  Nafas Portal          — React 19 / PHP / PWA',
    '  010  NafasTools            — Next.js / TypeScript',
    '',
    '  → Scroll the archive to examine selected work.',
    '',
  ],
  contact: [
    '',
    '  EMAIL      zrn_sany@yahoo.com',
    '  PHONE      09301221816',
    '',
    '  Preferred contact: Email',
    '  Response time:     < 24 hours',
    '',
  ],
  coffee: [
    '',
    '  ☕  Loading caffeine...',
    '',
    '  ██████████████████████████████ 100%',
    '',
    '  Design quality    +25%',
    '  Attention to detail  +40%',
    '  Font kerning sensitivity  +60%',
    '  Tolerance for bad briefs  -15%',
    '',
    '  ✓ Ready to design.',
    '',
  ],
};

const FA_COMMANDS: Record<Exclude<TerminalCommandId, 'clear'>, string[]> = {
  help: [
    '┌─ فرمان‌های موجود ─────────────────────────────',
    '│  help / راهنما      — نمایش این پیام',
    '│  whoami / کیستم    — نمایش پروفایل کاربر',
    '│  skills / مهارت‌ها  — فهرست توانایی‌های فنی',
    '│  projects / پروژه‌ها — مرور کارهای منتخب',
    '│  contact / تماس    — اطلاعات تماس',
    '│  coffee / قهوه     — سوخت ضروری',
    '│  clear / پاک       — پاک‌کردن خروجی ترمینال',
    '└───────────────────────────────────────────────',
  ],
  whoami: [
    '',
    '  نام      سعید زرینی',
    '  نقش      طراح گرافیک · متخصص بسته‌بندی · توسعه‌دهنده',
    '  تجربه    ۱۶+ سال (از ۱۳۸۶)',
    '  پایگاه   استودیوی مستقل — دورکارمحور',
    '  حالت     دقت و خلاقیت',
    '',
    '  «برای تحت‌تأثیر گذاشتن طراحی نمی‌کنم. برای کار کردن طراحی می‌کنم.»',
    '',
  ],
  skills: [
    '',
    '  ── طراحی ──────────────────────────────────────',
    '  ▸ Photoshop / Illustrator         ████████████ Master',
    '  ▸ InDesign / XD / CorelDRAW       ███████████░ Expert',
    '  ▸ After Effects / Premiere        █████████░░░ Advanced',
    '  ▸ Pharma Packaging / UI-UX        ████████████ Master',
    '',
    '  ── فرانت‌اند ──────────────────────────────────',
    '  ▸ React 18/19 · TypeScript        ██████████░░ Expert',
    '  ▸ Next.js · Vite · Tailwind       █████████░░░ Advanced',
    '',
    '  ── بک‌اند ─────────────────────────────────────',
    '  ▸ PHP · WordPress                 ████████████ Master',
    '  ▸ FastAPI · MySQL · PostgreSQL    █████████░░░ Advanced',
    '',
    '  ── بومی ───────────────────────────────────────',
    '  ▸ Kotlin · Jetpack Compose        ████████░░░░ Advanced',
    '  ▸ Tauri v2 · Rust                 ███████░░░░░ Advanced',
    '',
    '  ── هوش مصنوعی و ربات ──────────────────────────',
    '  ▸ Anthropic · OpenAI · Gemini     █████████░░░ Advanced',
    '  ▸ OpenRouter · Telegram · Bale    ████████░░░░ Advanced',
    '',
  ],
  projects: [
    '',
    '  001  DbsPulse              — FastAPI / React / Postgres',
    '  002  Second Brain (SOL)    — Kotlin / Compose / SQLCipher',
    '  003  DbsKeep v0.2.5        — Tauri v2 / Rust',
    '  004  Nafas AI              — React 19 / PHP 8 / MySQL',
    '  005  Nafas Chatbot Pro     — WordPress / Gemini',
    '  006  Elementor Carousel    — PHP / Elementor',
    '  007  EsiFit                — React 18 / TS / Vite',
    '  008  حساب‌یار               — PHP / MySQL / PWA',
    '  009  پورتال نفس            — React 19 / PHP / PWA',
    '  010  NafasTools            — Next.js / TypeScript',
    '',
    '  → برای بررسی کارهای منتخب، آرشیو را ورق بزنید.',
    '',
  ],
  contact: [
    '',
    '  ایمیل     zrn_sany@yahoo.com',
    '  تلفن      09301221816',
    '',
    '  تماس ترجیحی: ایمیل',
    '  زمان پاسخ:   کمتر از ۲۴ ساعت',
    '',
  ],
  coffee: [
    '',
    '  ☕  در حال بارگذاری کافئین...',
    '',
    '  ██████████████████████████████ 100%',
    '',
    '  کیفیت طراحی              +25%',
    '  دقت به جزئیات            +40%',
    '  حساسیت کرنینگ فونت       +60%',
    '  تحمل بریف‌های بد         -15%',
    '',
    '  ✓ آمادهٔ طراحی.',
    '',
  ],
};

export const terminalContent = {
  en: {
    windowTitle: 'saeed-design-system — terminal',
    closeAria: 'Close terminal',
    placeholder: 'type a command...',
    boot: [
      'SAEED DESIGN SYSTEM v1.0',
      'Initializing workspace...',
      '──────────────────────────────────────────',
      'Type "help" for available commands.',
      '',
    ],
    notFound: (cmd: string) =>
      `  Command not found: "${cmd}". Type "help" for available commands.`,
    aliases: {} as Record<string, TerminalCommandId>,
    commands: EN_COMMANDS,
  },
  fa: {
    windowTitle: 'saeed-design-system — terminal',
    closeAria: 'بستن ترمینال',
    placeholder: 'فرمانی بنویسید...',
    boot: [
      'سامانهٔ طراحی سعید v1.0',
      'در حال راه‌اندازی فضای کار...',
      '──────────────────────────────────────────',
      'برای فهرست فرمان‌ها «راهنما» یا help را تایپ کنید.',
      '',
    ],
    notFound: (cmd: string) =>
      `  فرمان یافت نشد: «${cmd}». «راهنما» یا help را تایپ کنید.`,
    aliases: {
      راهنما: 'help',
      کیستم: 'whoami',
      مهارت: 'skills',
      مهارت‌ها: 'skills',
      پروژه: 'projects',
      پروژه‌ها: 'projects',
      تماس: 'contact',
      قهوه: 'coffee',
      پاک: 'clear',
      پاکسازی: 'clear',
    } as Record<string, TerminalCommandId>,
    commands: FA_COMMANDS,
  },
};
