export const tickerContent = {
  en: [
    'Pharmaceutical Packaging',
    'Brand Identity',
    'Graphic Design',
    'AI Solutions',
    'Telegram & Bale Bots',
    'WordPress Development',
    'React Applications',
    'UI/UX Design',
    'Catalog Design',
    'Art Direction',
    'Brochure Design',
    'Visual Systems',
  ],
  fa: [
    'بسته‌بندی دارویی',
    'هویت برند',
    'طراحی گرافیک',
    'راه‌حل‌های هوش مصنوعی',
    'ربات تلگرام و بله',
    'توسعهٔ وردپرس',
    'اپلیکیشن‌های ری‌اکت',
    'طراحی رابط و تجربهٔ کاربری',
    'طراحی کاتالوگ',
    'مدیریت هنری',
    'طراحی بروشور',
    'سامانه‌های بصری',
  ],
};
